DoAn_CuaHangLaptop/Test/Areas/Admin/Controllers/HoaDonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Test.Data;
using Test.Models;

namespace Test.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class HoaDonController : Controller
    {
        private readonly LapTopContext _context;

        public HoaDonController(LapTopContext context)
        {
            _context = context;
        }

        // GET: Admin/HoaDon
        public IActionResult Index(int trangthai)
        {
            trangthai--;
            List<Hoadon> dsHd = new List<Hoadon>();
            if (trangthai == -1)
            {
                var query = from hd in _context.Hoadon select hd;
                dsHd = query.ToList();
            }
            else if (trangthai == 0)
            {
                var query = from hd in _context.Hoadon where hd.Trangthai == 0 select hd;
                dsHd = query.ToList();
            }
            else if (trangthai == 1)
            {
                var query = from hd in _context.Hoadon where hd.Trangthai == 1 select hd;
                dsHd = query.ToList();
            }
            else if (trangthai == 2)
            {
                var query = from hd in _context.Hoadon where hd.Trangthai == 2 select hd;
                dsHd = query.ToList();
            }
            else
            {
                var query = from hd in _context.Hoadon where hd.Trangthai == 3 select hd;
                dsHd = query.ToList();
            }
            return View(dsHd);

        }

        // GET: Admin/HoaDon/Details/5
        //public async Task<IActionResult> Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var cthd = await _context.Cthd
        //        .Include(c => c.MahdNavigation)
        //        .FirstOrDefaultAsync(m => m.Mahd == id);
        //    if (cthd == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(cthd);
        //}

        public IActionResult Details(int id)
        {

            List<Cthd> listdata = _context.Cthd.Where(cthd => cthd.Mahd == id).Select(cthd => new Cthd
            {
                Mahd = cthd.Mahd,
                Masp = cthd.Masp,
                MahdNavigation = cthd.MahdNavigation,
                MaspNavigation = cthd.MaspNavigation,
                Soluong = cthd.Soluong,

            }).ToList();
            foreach(var ct in listdata)
            {
                TempData["TongCong"] = ct.MahdNavigation.Tongtien?.ToString("#,##0 VND");
            }
            return View(listdata);
        }
        public IActionResult changeStatus(int mahd)
        {
            Hoadon result = (from hd in _context.Hoadon
                             where hd.Mahd == mahd
                             select hd).SingleOrDefault();

            result.Trangthai++;

            _context.SaveChanges();
            return RedirectToAction("Index", new { trangthai = 0 });
        }

        //// GET: Admin/HoaDon/Create
        //public IActionResult Create()
        //{
        //    ViewData["Makh"] = new SelectList(_context.Khachhang, "Makh", "Makh");
        //    ViewData["Mask"] = new SelectList(_context.Sukien, "Mask", "Mask");
        //    return View();
        //}

        //// POST: Admin/HoaDon/Create
        //// To protect from overposting attacks, enable the specific properties you want to bind to, for 
        //// more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Create([Bind("Mahd,Makh,Mask,Ngayhd,Nguoinhan,nhanvienmanv,Sdt,Diachigiaohang,Tongtien,Thanhtien,Trangthai")] Hoadon hoadon)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        _context.Add(hoadon);
        //        await _context.SaveChangesAsync();
        //        return RedirectToAction(nameof(Index));
        //    }
        //    ViewData["Makh"] = new SelectList(_context.Khachhang, "Makh", "Makh", hoadon.Makh);
        //    ViewData["Mask"] = new SelectList(_context.Sukien, "Mask", "Mask", hoadon.Mask);
        //    return View(hoadon);
        //}

        //// GET: Admin/HoaDon/Edit/5
        //public async Task<IActionResult> Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var hoadon = await _context.Hoadon.FindAsync(id);
        //    if (hoadon == null)
        //    {
        //        return NotFound();
        //    }
        //    ViewData["Makh"] = new SelectList(_context.Khachhang, "Makh", "Makh", hoadon.Makh);
        //    ViewData["Mask"] = new SelectList(_context.Sukien, "Mask", "Mask", hoadon.Mask);
        //    return View(hoadon);
        //}

        //// POST: Admin/HoaDon/Edit/5
        //// To protect from overposting attacks, enable the specific properties you want to bind to, for 
        //// more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Edit(int id, [Bind("Mahd,Makh,Mask,Ngayhd,Nguoinhan,nhanvienmanv,Sdt,Diachigiaohang,Tongtien,Thanhtien,Trangthai")] Hoadon hoadon)
        //{
        //    if (id != hoadon.Mahd)
        //    {
        //        return NotFound();
        //    }

        //    if (ModelState.IsValid)
        //    {
        //        try
        //        {
        //            _context.Update(hoadon);
        //            await _context.SaveChangesAsync();
        //        }
        //        catch (DbUpdateConcurrencyException)
        //        {
        //            if (!HoadonExists(hoadon.Mahd))
        //            {
        //                return NotFound();
        //            }
        //            else
        //            {
        //                throw;
        //            }
        //        }
        //        return RedirectToAction(nameof(Index));
        //    }
        //    ViewData["Makh"] = new SelectList(_context.Khachhang, "Makh", "Makh", hoadon.Makh);
        //    ViewData["Mask"] = new SelectList(_context.Sukien, "Mask", "Mask", hoadon.Mask);
        //    return View(hoadon);
        //}

        //// GET: Admin/HoaDon/Delete/5
        //public async Task<IActionResult> Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var hoadon = await _context.Hoadon
        //        .Include(h => h.MakhNavigation)
        //        .Include(h => h.MaskNavigation)
        //        .FirstOrDefaultAsync(m => m.Mahd == id);
        //    if (hoadon == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(hoadon);
        //}

        //// POST: Admin/HoaDon/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> DeleteConfirmed(int id)
        //{
        //    var hoadon = await _context.Hoadon.FindAsync(id);
        //    _context.Hoadon.Remove(hoadon);
        //    await _context.SaveChangesAsync();
        //    return RedirectToAction(nameof(Index));
        //}

        //private bool HoadonExists(int id)
        //{
        //    return _context.Hoadon.Any(e => e.Mahd == id);
        //}
    }
}

DoAn_CuaHangLaptop/Test/Controllers/HoadonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Test.Data;
using Test.Models;

namespace Test.Controllers
{
    public class HoadonController : Controller
    {
        private readonly LapTopContext _context;

        private readonly UserManager<AppUser> _userManager;

        public HoadonController(LapTopContext context, UserManager<AppUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }
        private async Task<AppUser> GetCurrentUser()
        {
            return await _userManager.GetUserAsync(HttpContext.User);
        }

        // GET: Hoadon
        public async Task<IActionResult> Index()
        {
            var lapTopContext = _context.Hoadon.Include(h => h.MakhNavigation)/*.Include(h => h.ManvNavigation).Include(h => h.MaskNavigation)*/;
            return View(await lapTopContext.ToListAsync());
        }

        // GET: Hoadon/Details/5
        public async Task<IActionResult> Details(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hoadon = await _context.Hoadon
                .Include(h => h.MakhNavigation)
                //.Include(h => h.ManvNavigation)
                .Include(h => h.MaskNavigation)
                .FirstOrDefaultAsync(m => m.Mahd == id);
            if (hoadon == null)
            {
                return NotFound();
            }

            return View(hoadon);
        }

        // GET: Hoadon/Create
        public IActionResult Create()
        {
            ViewData["Makh"] = new SelectList(_context.Khachhang, "Makh", "Makh");
            //ViewData["Manv"] = new SelectList(_context.Nhanvien, "Manv", "Manv");
            ViewData["Mask"] = new SelectList(_context.Sukien, "Mask", "Mask");
            return View();
        }

        // POST: Hoadon/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Mahd,Makh,Mask,Ngayhd,Nguoinhan,Sdt,Diachigiaohang,Tongtien,Thanhtien,Trangthai")] Hoadon hoadon)
        {
            if (ModelState.IsValid)
            {
                _context.Add(hoadon);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Makh"] = new SelectList(_context.Khachhang, "Makh", "Makh", hoadon.Makh);
            //ViewData["Manv"] = new SelectList(_context.Nhanvien, "Manv", "Manv", hoadon.Manv);
            ViewData["Mask"] = new SelectList(_context.Sukien, "Mask", "Mask", hoadon.Mask);
            return View(hoadon);
        }

        // GET: Hoadon/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hoadon = await _context.Hoadon.FindAsync(id);
            if (hoadon == null)
            {
                return NotFound();
            }
            ViewData["Makh"] = new SelectList(_context.Khachhang, "Makh", "Makh", hoadon.Makh);
            //ViewData["Manv"] = new SelectList(_context.Nhanvien, "Manv", "Manv", hoadon.Manv);
            ViewData["Mask"] = new SelectList(_context.Sukien, "Mask", "Mask", hoadon.Mask);
            return View(hoadon);
        }

        // POST: Hoadon/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Mahd,Makh,Mask,Ngayhd,Nguoinhan,Sdt,Diachigiaohang,Tongtien,Thanhtien,Trangthai")] Hoadon hoadon)
        {
            if (id != hoadon.Mahd)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(hoadon);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!HoadonExists(hoadon.Mahd))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Makh"] = new SelectList(_context.Khachhang, "Makh", "Makh", hoadon.Makh);
            //ViewData["Manv"] = new SelectList(_context.Nhanvien, "Manv", "Manv", hoadon.Manv);
            ViewData["Mask"] = new SelectList(_context.Sukien, "Mask", "Mask", hoadon.Mask);
            return View(hoadon);
        }

        // GET: Hoadon/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hoadon = await _context.Hoadon
                .Include(h => h.MakhNavigation)
                //.Include(h => h.ManvNavigation)
                .Include(h => h.MaskNavigation)
                .FirstOrDefaultAsync(m => m.Mahd == id);
            if (hoadon == null)
            {
                return NotFound();
            }

            return View(hoadon);
        }

        // POST: Hoadon/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var hoadon = await _context.Hoadon.FindAsync(id);
            _context.Hoadon.Remove(hoadon);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool HoadonExists(int id)
        {
            return _context.Hoadon.Any(e => e.Mahd == id);
        }

        //Lay hóa đơn trạng thái chờ xác nhận
        public async Task<IActionResult> HDChoXNAsync()
        {
            var user = await GetCurrentUser();
            string id = user.Id;
            List<Hoadon> listdata = _context.Hoadon.Where(hd => hd.Trangthai == 0).Where(hd => hd.Makh == id).Select(hd => new Hoadon
            {
                Mahd = hd.Mahd,
                Makh = hd.Makh,
                Mask = hd.Mask,
                Ngayhd = hd.Ngayhd,
                Nguoinhan = hd.Nguoinhan,
                nhanvienmanv = hd.nhanvienmanv,
                Sdt = hd.Sdt,
                Diachigiaohang = hd.Diachigiaohang,
                Tongtien = hd.Tongtien,
                Thanhtien = hd.Thanhtien,

            }).ToList();


            return View(listdata);
        }

        //Lấy hóa đơn trạng thái đã xác nhận
        public async Task<IActionResult> HDXNAsync()
        {
            var user = await GetCurrentUser();
            string id = user.Id;
            List<Hoadon> listdata = _context.Hoadon.Where(hd => hd.Trangthai == 1).Where(hd => hd.Makh == id).Select(hd => new Hoadon
            {
                Mahd = hd.Mahd,
                Makh = hd.Makh,
                Mask = hd.Mask,
                Ngayhd = hd.Ngayhd,
                Nguoinhan = hd.Nguoinhan,
                nhanvienmanv = hd.nhanvienmanv,
                Sdt = hd.Sdt,
                Diachigiaohang = hd.Diachigiaohang,
                Tongtien = hd.Tongtien,
                Thanhtien = hd.Thanhtien,

            }).ToList();


            return View(listdata);
        }

        //Lay hóa đơn trạng thái đang giao
        public async Task<IActionResult> HDDangGiaoAsync()
        {

            var user = await GetCurrentUser();
            string id = user.Id;
            List<Hoadon> listdata = _context.Hoadon.Where(hd => hd.Trangthai == 2).Where(hd => hd.Makh == id).Select(hd => new Hoadon
            {
                Mahd = hd.Mahd,
                Makh = hd.Makh,
                Mask = hd.Mask,
                Ngayhd = hd.Ngayhd,
                Nguoinhan = hd.Nguoinhan,
                nhanvienmanv = hd.nhanvienmanv,
                Sdt = hd.Sdt,
                Diachigiaohang = hd.Diachigiaohang,
                Tongtien = hd.Tongtien,
                Thanhtien = hd.Thanhtien,

            }).ToList();


            return View(listdata);
        }

        //Lay hóa đơn trạng thái đã giao
        public async Task<IActionResult> HDDaGiaoAsync()
        {

            var user = await GetCurrentUser();
            string id = user.Id;
            List<Hoadon> listdata = _context.Hoadon.Where(hd => hd.Trangthai == 3).Where(hd => hd.Makh == id).Select(hd => new Hoadon
            {
                Mahd = hd.Mahd,
                Makh = hd.Makh,
                Mask = hd.Mask,
                Ngayhd = hd.Ngayhd,
                Nguoinhan = hd.Nguoinhan,
                nhanvienmanv = hd.nhanvienmanv,
                Sdt = hd.Sdt,
                Diachigiaohang = hd.Diachigiaohang,
                Tongtien = hd.Tongtien,
                Thanhtien = hd.Thanhtien,

            }).ToList();


            return View(listdata);
        }
    }
}

DoAn_CuaHangLaptop/Test/Areas/Admin/Views/HoaDon/Details.cshtml
@model IEnumerable<Test.Models.Cthd>
@{
    ViewData["Title"] = "Details";
}



<div class="container-fluid">

    <!-- Page Heading -->
    <!-- DataTales Example -->
    <div class="card shadow mb-4">

        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Chi tiết hóa đơn</h6>
        </div>

        <p></p>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Mã hóa đơn</th>
                            <th>Tên người nhận</th>
                            <th>Ngày hóa đơn</th>
                            <th>Tên sản phẩm</th>
                            <th>Số lượng</th>
                            <th>Đơn giá</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.Mahd</td>
                                <td>@item.MahdNavigation.Nguoinhan</td>
                                <td>@item.MahdNavigation.Ngayhd?.ToString("dd/MM/yyyy")</td>
                                <td>@item.MaspNavigation.Tensp</td>
                                <td>@item.Soluong</td>
                                <td>@item.MaspNavigation.Dongia?.ToString("#,##0 VND")</td>
                            </tr>

                        }
                        <tr></tr>
                    </tbody>
                </table>
                          <div style="display:flex; justify-content:end" >Tổng cộng: @TempData["TongCong"]</div>
            </div>
        </div>
    </div>

<div>
    <a asp-action="Index">Back to List</a>
</div>
</div>


<style>
    table.table-bordered.dataTable tbody td {
        border-bottom-width: thin;
        border-left-width: thin;
    }
    table.table-bordered.dataTable th {
        border-left-width: thin;
    }
</style>

DoAn_CuaHangLaptop/Test/Areas/Admin/Views/HoaDon/Index.cshtml
@model IEnumerable<Test.Models.Hoadon>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid">

    <!-- Page Heading -->
    <!-- DataTales Example -->
    <div class="card shadow mb-4">

        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Hóa đơn</h6>
            <div class="d-flex justify-content-end">
                <a asp-action="Index" asp-controller="HoaDon" asp-area="admin" asp-route-trangthai="1" class="btn btn-primary mr-1">
                    Đơn hàng chưa xác nhận
                </a>
                <a asp-action="Index" asp-controller="HoaDon" asp-area="admin" asp-route-trangthai="2" class="btn btn-secondary mr-1">
                    Đơn hàng đã xác nhận
                </a>
                <a asp-action="Index" asp-controller="HoaDon" asp-area="admin" asp-route-trangthai="3" class="btn btn-info mr-1">
                    Đơn hàng đang giao
                </a>
                <a asp-action="Index" asp-controller="HoaDon" asp-area="admin" asp-route-trangthai="4" class="btn btn-success">
                    Đơn hàng đã giao
                </a>
            </div>
        </div>

        <p></p>
        
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>
                                Ngày hóa đơn
                            </th>
                            <th>
                               Người nhận
                            </th>
                            <th>
                                Số điện thoại
                            </th>
                            <th>
                                Địa chỉ giao hàng
                            </th>
                            <th>
                                Tổng tiền
                            </th>
                            <th>
                                Trạng thái
                            </th>
                            <th>
                                Tác vụ
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                        <tr>
                            <td>
                                @item.Ngayhd?.ToString("dd/MM/yyyy")
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Nguoinhan)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Sdt)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Diachigiaohang)
                            </td>
                            <td>
                                @item.Tongtien?.ToString("#,##0 VND")
                            </td>

                            @if (@item.Trangthai == 0)
                            {
                                <td>Chưa xác nhận</td>
                            }
                            else if (@item.Trangthai == 1)
                            {
                                <td>Đã xác nhận</td>
                            }
                            else if (@item.Trangthai == 2)
                            {
                                <td>Đang giao hàng</td>
                            }
                            else
                            {
                                <td>Đã giao hàng</td>

                            }

                            <td>
                                <a asp-controller="HoaDon" asp-action="Details" asp-route-id="@item.Mahd" class="btn btn-info">Chi tiết</a>
                                @if (item.Trangthai != 3)
                                {
                                    <a asp-controller="HoaDon" asp-action="changeStatus" asp-route-mahd="@item.Mahd" class="btn btn-warning">Xác nhận đơn hàng</a>
                                }

                            </td>
                        </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>