DoAn_CuaHangLaptop/Test/Areas/Admin/Controllers/HoaDonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Test.Data;
using Test.Models;

namespace Test.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class HoaDonController : Controller
    {
        private readonly LapTopContext _context;

        public HoaDonController(LapTopContext context)
        {
            _context = context;
        }

        // GET: Admin/HoaDon
        public IActionResult Index(int trangthai)
        {
            trangthai--;
            List<Hoadon> dsHd = new List<Hoadon>();
            if (trangthai == -1)
            {
                var query = from hd in _context.Hoadon select hd;
                dsHd = query.ToList();
            }
            else if (trangthai == 0)
            {
                var query = from hd in _context.Hoadon where hd.Trangthai == 0 select hd;
                dsHd = query.ToList();
            }
            else if (trangthai == 1)
            {
                var query = from hd in _context.Hoadon where hd.Trangthai == 1 select hd;
                dsHd = query.ToList();
            }
            else if (trangthai == 2)
            {
                var query = from hd in _context.Hoadon where hd.Trangthai == 2 select hd;
                dsHd = query.ToList();
            }
            else
            {
                var query = from hd in _context.Hoadon where hd.Trangthai == 3 select hd;
                dsHd = query.ToList();
            }
            return View(dsHd);

        }

        // GET: Admin/HoaDon/Details/5
        //public async Task<IActionResult> Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var cthd = await _context.Cthd
        //        .Include(c => c.MahdNavigation)
        //        .FirstOrDefaultAsync(m => m.Mahd == id);
        //    if (cthd == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(cthd);
        //}

        public IActionResult Details(int id)
        {

            List<Cthd> listdata = _context.Cthd.Where(cthd => cthd.Mahd == id).Select(cthd => new Cthd
            {
                Mahd = cthd.Mahd,
                Masp = cthd.Masp,
                MahdNavigation = cthd.MahdNavigation,
                MaspNavigation = cthd.MaspNavigation,
                Soluong = cthd.Soluong,

            }).ToList();
            foreach(var ct in listdata)
            {
                TempData["TongCong"] = ct.MahdNavigation.Tongtien?.ToString("#,##0 VND");
            }
            return View(listdata);
        }
        public IActionResult changeStatus(int mahd)
        {
            Hoadon result = (from hd in _context.Hoadon
                             where hd.Mahd == mahd
                             select hd).SingleOrDefault();

            result.Trangthai++;

            _context.SaveChanges();
            return RedirectToAction("Index", new { trangthai = 0 });
        }

        //// GET: Admin/HoaDon/Create
        //public IActionResult Create()
        //{
        //    ViewData["Makh"] = new SelectList(_context.Khachhang, "Makh", "Makh");
        //    ViewData["Mask"] = new SelectList(_context.Sukien, "Mask", "Mask");
        //    return View();
        //}

        //// POST: Admin/HoaDon/Create
        //// To protect from overposting attacks, enable the specific properties you want to bind to, for 
        //// more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Create([Bind("Mahd,Makh,Mask,Ngayhd,Nguoinhan,nhanvienmanv,Sdt,Diachigiaohang,Tongtien,Thanhtien,Trangthai")] Hoadon hoadon)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        _context.Add(hoadon);
        //        await _context.SaveChangesAsync();
        //        return RedirectToAction(nameof(Index));
        //    }
        //    ViewData["Makh"] = new SelectList(_context.Khachhang, "Makh", "Makh", hoadon.Makh);
        //    ViewData["Mask"] = new SelectList(_context.Sukien, "Mask", "Mask", hoadon.Mask);
        //    return View(hoadon);
        //}

        //// GET: Admin/HoaDon/Edit/5
        //public async Task<IActionResult> Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var hoadon = await _context.Hoadon.FindAsync(id);
        //    if (hoadon == null)
        //    {
        //        return NotFound();
        //    }
        //    ViewData["Makh"] = new SelectList(_context.Khachhang, "Makh", "Makh", hoadon.Makh);
        //    ViewData["Mask"] = new SelectList(_context.Sukien, "Mask", "Mask", hoadon.Mask);
        //    return View(hoadon);
        //}

        //// POST: Admin/HoaDon/Edit/5
        //// To protect from overposting attacks, enable the specific properties you want to bind to, for 
        //// more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Edit(int id, [Bind("Mahd,Makh,Mask,Ngayhd,Nguoinhan,nhanvienmanv,Sdt,Diachigiaohang,Tongtien,Thanhtien,Trangthai")] Hoadon hoadon)
        //{
        //    if (id != hoadon.Mahd)
        //    {
        //        return NotFound();
        //    }

        //    if (ModelState.IsValid)
        //    {
        //        try
        //        {
        //            _context.Update(hoadon);
        //            await _context.SaveChangesAsync();
        //        }
        //        catch (DbUpdateConcurrencyException)
        //        {
        //            if (!HoadonExists(hoadon.Mahd))
        //            {
        //                return NotFound();
        //            }
        //            else
        //            {
        //                throw;
        //            }
        //        }
        //        return RedirectToAction(nameof(Index));
        //    }
        //    ViewData["Makh"] = new SelectList(_context.Khachhang, "Makh", "Makh", hoadon.Makh);
        //    ViewData["Mask"] = new SelectList(_context.Sukien, "Mask", "Mask", hoadon.Mask);
        //    return View(hoadon);
        //}

        //// GET: Admin/HoaDon/Delete/5
        //public async Task<IActionResult> Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var hoadon = await _context.Hoadon
        //        .Include(h => h.MakhNavigation)
        //        .Include(h => h.MaskNavigation)
        //        .FirstOrDefaultAsync(m => m.Mahd == id);
        //    if (hoadon == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(hoadon);
        //}

        //// POST: Admin/HoaDon/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> DeleteConfirmed(int id)
        //{
        //    var hoadon = await _context.Hoadon.FindAsync(id);
        //    _context.Hoadon.Remove(hoadon);
        //    await _context.SaveChangesAsync();
        //    return RedirectToAction(nameof(Index));
        //}

        //private bool HoadonExists(int id)
        //{
        //    return _context.Hoadon.Any(e => e.Mahd == id);
        //}
    }
}

DoAn_CuaHangLaptop/Test/Areas/Admin/Pages/Role/create.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Test.Data;

namespace App.Admin.Role
{
    //[Authorize(Roles = "admin")]

    public class CreateModel : RolePageModel
    {
        public CreateModel(RoleManager<IdentityRole> roleManager, LapTopContext myBlogContext) : base(roleManager, myBlogContext)
        {

        }

        public class InputModel
        {
            [Display(Name = "Tên của role")]
            [Required(ErrorMessage = "Phải nhập {0}")]
            [StringLength(200, MinimumLength = 3, ErrorMessage = "{0} phải dài {2} đến {1} ký tự")]
            public string Name { get; set; }
        }

        [BindProperty]
        // binding dữ liệu khi người dùng summit
        public InputModel Input { set; get; }

        public void OnGet()
        {
        }
        // bat dong bo async
        // khi an tao moi thi OnPostAsync duoc ta
        public async Task<IActionResult> OnPostAsync()
        {
            // neu du lieu ko phu hop => page
            if (!ModelState.IsValid)
            {
                return Page();
            }

            var newRole = new IdentityRole(Input.Name.ToLower());
            var result = await _roleManager.CreateAsync(newRole);
            if (result.Succeeded)
            {
                StatusMessage = $"Bạn vừa tạo role mới: {Input.Name}";
                return RedirectToPage("./Index");
            }
            else
            {
                result.Errors.ToList().ForEach(error => {
                    ModelState.AddModelError(string.Empty, error.Description);
                });
            }



            return Page();
        }
    }
}

DoAn_CuaHangLaptop/Test/Areas/Admin/Pages/Role/delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Test.Data;

namespace App.Admin.Role
{
    [Authorize(Roles = "admin")]
    public class DeleteModel : RolePageModel
    {
        public DeleteModel(RoleManager<IdentityRole> roleManager, LapTopContext myBlogContext) : base(roleManager, myBlogContext)
        {

        }


        public IdentityRole role { get; set; }

        public async Task<IActionResult> OnGet(string roleid)
        {
            if (roleid == null) return NotFound("Không tìm thấy role");

            role = await _roleManager.FindByIdAsync(roleid);
            if (role == null)
            {
                return NotFound("Không tìm thấy role");
            }
            return Page();
        }



        public async Task<IActionResult> OnPostAsync(string roleid)
        {
            if (roleid == null) return NotFound("Không tìm thấy role");
            role = await _roleManager.FindByIdAsync(roleid);
            if (role == null) return NotFound("Không tìm thấy role");


            var result = await _roleManager.DeleteAsync(role);

            if (result.Succeeded)
            {
                StatusMessage = $"Bạn vừa xóa: {role.Name}";
                return RedirectToPage("./Index");
            }
            else
            {
                result.Errors.ToList().ForEach(error => {
                    ModelState.AddModelError(string.Empty, error.Description);
                });
            }
            return Page();
        }
    }
}

DoAn_CuaHangLaptop/Test/Controllers/CthdController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Test.Data;
using Test.Models;

namespace Test.Controllers
{
    public class CthdController : Controller
    {
        private readonly LapTopContext _context;

        public CthdController(LapTopContext context)
        {
            _context = context;
        }

        // GET: Cthd
        public async Task<IActionResult> Index()
        {
            var lapTopContext = _context.Cthd.Include(c => c.MahdNavigation).Include(c => c.MaspNavigation);
            return View(await lapTopContext.ToListAsync());
        }

        // GET: Cthd/Details/5
        public async Task<IActionResult> Details(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cthd = await _context.Cthd
                .Include(c => c.MahdNavigation)
                .Include(c => c.MaspNavigation)
                .FirstOrDefaultAsync(m => m.Mahd == id);
            if (cthd == null)
            {
                return NotFound();
            }

            return View(cthd);
        }

        // GET: Cthd/Create
        public IActionResult Create()
        {
            ViewData["Mahd"] = new SelectList(_context.Hoadon, "Mahd", "Mahd");
            ViewData["Masp"] = new SelectList(_context.Sanpham, "Masp", "Masp");
            return View();
        }

        // POST: Cthd/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Mahd,Masp,Soluong")] Cthd cthd)
        {
            if (ModelState.IsValid)
            {
                _context.Add(cthd);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Mahd"] = new SelectList(_context.Hoadon, "Mahd", "Mahd", cthd.Mahd);
            ViewData["Masp"] = new SelectList(_context.Sanpham, "Masp", "Masp", cthd.Masp);
            return View(cthd);
        }

        // GET: Cthd/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cthd = await _context.Cthd.FindAsync(id);
            if (cthd == null)
            {
                return NotFound();
            }
            ViewData["Mahd"] = new SelectList(_context.Hoadon, "Mahd", "Mahd", cthd.Mahd);
            ViewData["Masp"] = new SelectList(_context.Sanpham, "Masp", "Masp", cthd.Masp);
            return View(cthd);
        }

        // POST: Cthd/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Mahd,Masp,Soluong")] Cthd cthd)
        {
            if (id != cthd.Mahd)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cthd);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CthdExists(cthd.Mahd))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Mahd"] = new SelectList(_context.Hoadon, "Mahd", "Mahd", cthd.Mahd);
            ViewData["Masp"] = new SelectList(_context.Sanpham, "Masp", "Masp", cthd.Masp);
            return View(cthd);
        }

        // GET: Cthd/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cthd = await _context.Cthd
                .Include(c => c.MahdNavigation)
                .Include(c => c.MaspNavigation)
                .FirstOrDefaultAsync(m => m.Mahd == id);
            if (cthd == null)
            {
                return NotFound();
            }

            return View(cthd);
        }

        // POST: Cthd/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var cthd = await _context.Cthd.FindAsync(id);
            _context.Cthd.Remove(cthd);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CthdExists(int id)
        {
            return _context.Cthd.Any(e => e.Mahd == id);
        }

        public IActionResult CTHD(int mahd)
        {

            List<Cthd> listdata = _context.Cthd.Where(cthd => cthd.Mahd == mahd).Select(cthd => new Cthd
            {
                Mahd = cthd.Mahd,
                Masp = cthd.Masp,
                MahdNavigation = cthd.MahdNavigation,
                MaspNavigation = cthd.MaspNavigation,
                Soluong = cthd.Soluong,
            }).ToList();


            return View(listdata);
        }
    }
}

DoAn_CuaHangLaptop/Test/Views/Hoadon/Create.cshtml
@model Test.Models.Hoadon

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Hoadon</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Mahd" class="control-label"></label>
                <input asp-for="Mahd" class="form-control" />
                <span asp-validation-for="Mahd" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Makh" class="control-label"></label>
                <select asp-for="Makh" class="form-control" asp-items="ViewBag.Makh"></select>
            </div>
            @*<div class="form-group">
            <label asp-for="Manv" class="control-label"></label>
            <select asp-for="Manv" class ="form-control" asp-items="ViewBag.Manv"></select>
        </div>*@
            <div class="form-group">
                <label asp-for="Mask" class="control-label"></label>
                <select asp-for="Mask" class="form-control" asp-items="ViewBag.Mask"></select>
            </div>
            <div class="form-group">
                <label asp-for="Ngayhd" class="control-label"></label>
                <input asp-for="Ngayhd" class="form-control" />
                <span asp-validation-for="Ngayhd" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nguoinhan" class="control-label"></label>
                <input asp-for="Nguoinhan" class="form-control" />
                <span asp-validation-for="Nguoinhan" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sdt" class="control-label"></label>
                <input asp-for="Sdt" class="form-control" />
                <span asp-validation-for="Sdt" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Diachigiaohang" class="control-label"></label>
                <input asp-for="Diachigiaohang" class="form-control" />
                <span asp-validation-for="Diachigiaohang" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tongtien" class="control-label"></label>
                <input asp-for="Tongtien" class="form-control" />
                <span asp-validation-for="Tongtien" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Thanhtien" class="control-label"></label>
                <input asp-for="Thanhtien" class="form-control" />
                <span asp-validation-for="Thanhtien" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Trangthai" class="control-label"></label>
                <input asp-for="Trangthai" class="form-control" />
                <span asp-validation-for="Trangthai" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DoAn_CuaHangLaptop/Test/Views/Hoadon/Delete.cshtml
@model Test.Models.Hoadon

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Hoadon</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Ngayhd)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Ngayhd)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nguoinhan)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nguoinhan)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Sdt)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Sdt)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Diachigiaohang)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Diachigiaohang)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Tongtien)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Tongtien)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Thanhtien)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Thanhtien)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Trangthai)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Trangthai)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.MakhNavigation)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.MakhNavigation.Makh)
        </dd>
        @*<dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ManvNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ManvNavigation.Manv)
        </dd class>*@
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.MaskNavigation)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.MaskNavigation.Mask)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Mahd" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

DoAn_CuaHangLaptop/Test/Views/Hoadon/HDChoXN.cshtml
@model IEnumerable<Test.Models.Hoadon>

@{
    ViewData["Title"] = "HDChoXN";
    Layout = "~/Areas/Identity/Pages/Account/Manage/_Layout.cshtml";
}


<table class="table">
    <thead>
        <tr>
            <th>
                <label>Ngày hóa đơn</label>
            </th>
            <th>
                Người nhận
            </th>
            <th>
               Số điện thoại
            </th>
            <th>
                Địa chỉ giao hàng
            </th>
            <th>
                Thành tiền
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @item.Ngayhd?.ToString("dd/MM/yyyy")
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nguoinhan)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Sdt)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Diachigiaohang)
            </td>
            <td>
                @item.Thanhtien?.ToString("#,### VND")
            </td>
            <td>
                <a asp-controller="Cthd" asp-action="CTHD" asp-route-mahd="@item.Mahd" >Chi tiết</a> 
            </td>
        </tr>
}
    </tbody>
</table>

DoAn_CuaHangLaptop/Test/Views/Hoadon/HDDaGiao.cshtml
@model IEnumerable<Test.Models.Hoadon>

@{
    ViewData["Title"] = "HDDaGiao";
    Layout = "~/Areas/Identity/Pages/Account/Manage/_Layout.cshtml";
}

<table class="table">
    <thead>
        <tr>
            <th>
                <label>Ngày hóa đơn</label>
            </th>
            <th>
                Người nhận
            </th>
            <th>
                Số điện thoại
            </th>
            <th>
                Địa chỉ giao hàng
            </th>
            <th>
                Thành tiền
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @item.Ngayhd?.ToString("dd/MM/yyyy")
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nguoinhan)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Sdt)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Diachigiaohang)
            </td>
            <td>
                @item.Thanhtien?.ToString("#,### VND")
            </td>
            <td>
                <a asp-controller="Cthd" asp-action="CTHD" asp-route-mahd="@item.Mahd" >Chi tiết</a>
            </td>
        </tr>
}
    </tbody>
</table>

DoAn_CuaHangLaptop/Test/Views/Hoadon/HDDangGiao.cshtml
@model IEnumerable<Test.Models.Hoadon>

@{
    ViewData["Title"] = "HDDangGiao";
    Layout = "~/Areas/Identity/Pages/Account/Manage/_Layout.cshtml";
}


<table class="table">
    <thead>
        <tr>
            <th>
               Ngày hóa đơn
            </th>
            <th>
                Người nhận
            </th>
            <th>
                Số điện thoại
            </th>
            <th>
                Địa chỉ giao hàng
            </th>
            <th>
                Thành tiền
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @item.Ngayhd?.ToString("dd/MM/yyyy")
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nguoinhan)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Sdt)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Diachigiaohang)
            </td>
            <td>
                @item.Thanhtien?.ToString("#,### VND")
            </td>
            <td>
                <a asp-controller="Cthd" asp-action="CTHD" asp-route-mahd="@item.Mahd" >Chi tiết</a>
            </td>
        </tr>
}
    </tbody>
</table>

DoAn_CuaHangLaptop/Test/Views/Hoadon/HDXN.cshtml
@model IEnumerable<Test.Models.Hoadon>

@{
    ViewData["Title"] = "HDXN";
    Layout = "~/Areas/Identity/Pages/Account/Manage/_Layout.cshtml";
}

<table class="table">
    <thead>
        <tr>
            <th>
               Ngày hóa đơn
            </th>
            <th>
                Người nhận
            </th>
            <th>
                Số điện thoại
            </th>
            <th>
                Địa chỉ giao hàng
            </th>
            <th>
                Thành tiền
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @item.Ngayhd?.ToString("dd/MM/yyyy")
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nguoinhan)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Sdt)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Diachigiaohang)
            </td>
            <td>
                @item.Thanhtien?.ToString("#,### VND")
            </td>
            <td>
                <a asp-controller="Cthd" asp-action="CTHD" asp-route-mahd="@item.Mahd">Chi tiết</a>
            </td>
        </tr>
}
    </tbody>
</table>